### ISSUE TITLE
Zorg voor een duidelijkere structuur in je client-side JavaScript

### ISSUE THREAD

**Issue by joostf** [vsheo/look-and-feel-corporate-identity#10]
Kijk eens bij de [JavaScript conventies van FDND Agency](https://github.com/fdnd-agency/.github/wiki/Conventies#javascript), wellicht helpt je dat om beter navolgbare JavaScript te schrijven.

**Comment by vsheo** [comment]
Ik heb mijn structuur aangepast naar:
-variables
-code
-functies

Ik heb variables binnen functies.
Het is me niet gelukt om mijn code werkend te houden toen ik die buiten de functies probeerde te declareren.
https://github.com/vsheo/look-and-feel-corporate-identity/blob/b425cf3a90061752c842c42610a33bc1012f3160/scripts/sectionSnap.js#L24C1-L36C2

**Comment by joostf** [comment]
De structuur die je hebt toegepast kan je voor elke scope doorvoeren. Een functie heeft een eigen scope, dus alle variabelen die bij de betreffende functie horen, en niet erbuiten nodig zijn, kan je weer volgens het zelfde principe bovenaan zetten, etc..
